server:  
  port: ${PORT:8080}

eureka:  
  instance:
    hostname: https://beam-hotels-discovery.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  
